# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "ArchiWorkshop CI"

on:
  push:
    branches: [ "main" ]
    paths: [ 'Projects/ArchiWorkshop/Src/**', 'Projects/ArchiWorkshop/Tests/**', '.github/workflows/dotnet-ci.yml' ]
    # paths-ignore:
    #     - '**.md'
    #     - '**.pptx'
    #     - '**.png'

jobs:
  build:
    name: Build

    strategy:
        matrix:
            # os: [ ubuntu-22.04 ]
            dotnet-version: [ '8.0.x' ]
            configuration: [ Release ]

    runs-on: ubuntu-22.04

    env:
        solution_dir: ./Projects/ArchiWorkshop
        solution_path: ./Projects/ArchiWorkshop/ArchiWorkshop.sln

    steps:
        # 형상관리 최신 소스 받기
        - name: Checkout
          uses: actions/checkout@v3

        # Git Commit SHA 얻기
        #   - Deprecating save-state and set-output commands: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        #   - GitHub Actions에서 output 변수의 문법 변경: https://blog.outsider.ne.kr/1651
        #   - Github Actions and creating a short SHA hash: https://dev.to/hectorleiva/github-actions-and-creating-a-short-sha-hash-8b7
        #
        # ${{ steps.vars.outputs.short_sha }}
        - name: Set Short Git Commit SHA
          id: vars
          run: |
            calculatedSha=$(git rev-parse --short ${{ github.sha }})
            echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT

        # .NET SDK 설치
        - name: Setup .NET SDK ${{ matrix.dotnet-version }}
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ matrix.dotnet-version }}

        # 패키지 복원
        - name: Restore NuGet Packages
          run: |
            dotnet restore ${{ env.solution_path }}

        # 빌드
        - name: Build
          run: |
            dotnet build ${{ env.solution_path }} \
                --configuration ${{ matrix.configuration }} \
                --no-restore

        #
        # 테스트 결과 폴더 구성
        #
        #  /home/runner/work/ArchiWorkshop
        #    /ArchiWorkshop                                     // 저장소 Root
        #    /Projects
        #    /ArchiWorkshop                                     // 솔루션 Root
        #       /TestResults                                    // 테스트 자동화 결과
        #           /19f5be57-f7f1-4902-a22d-ca2dcd8fdc7a       // dotnet test: 코드 커버리지 N개           <- Artifacts 업로드
        #               /coverage.cobertura.xml
        #
        #               /merged-coverage.cobertura.xml          // dotnet-coverage: Merged 코드 커버리지
        #
        #               /CodeCoverageReport                     // ReportGenerator: 코드 커버리지 Markdown  <- Summary 업로드
        #                   /SummaryGithub.md

        - name: Test
          run: |
            dotnet test ${{ env.solution_path }} \
                --configuration ${{ matrix.configuration }} \
                --results-directory ${{ env.solution_dir }}/TestResults \
                --no-build \
                --collect "XPlat Code Coverage" \
                --verbosity normal

        # dotnet-coverage 도구 설치
        - name: Install dotnet-coverage
          run: dotnet tool install -g dotnet-coverage

        # Merged 코드 커버리지 생성
        - name: Convert .coverage report to cobertura
          run: |
            dotnet-coverage merge ${{ env.solution_dir }}/TestResults/**/*.cobertura.xml \
                -f cobertura \
                -o ${{ env.solution_dir }}/TestResults/merged-coverage.cobertura.xml

        # 코드 커버리지 보고서 생성
        - name: ReportGenerator
          uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
          with:
            reports: '${{ env.solution_dir }}/TestResults/merged-coverage.cobertura.xml'
            targetdir: '${{ env.solution_dir }}/TestResults/CodeCoverageReport'
            reporttypes: 'MarkdownSummaryGithub'

        # 코드 커버리지 Markdown 파일 Summary 업로드
        - name: Upload Coverage Into GitHub Actions Summary
          run: cat ${{ env.solution_dir }}/TestResults/CodeCoverageReport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

        # 코드 커버리지 .cobertura 파일 Artifacts 업로드
        - name: Upload CodeCoverageResults Files Into GitHub Actions Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: CodeCoverageReport_${{ matrix.dotnet-version }}_sha-${{ steps.vars.outputs.short_sha }}
            path: ${{ env.solution_dir }}/TestResults/**/*.cobertura.xml