# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "ArchiWorkshop CI"

# TODO: PR일 때 코드 커버리지 댓글 추가
on:
  push:
    branches: [ "main" ]
    paths: [ 'Projects/ArchiWorkshop/Src/**', 'Projects/ArchiWorkshop/Tests/**', '.github/workflows/dotnet-ci.yml' ]
    # TODO: 특정 확장자 Actions 제외
    # paths-ignore:
    #     - '**.md'
    #     - '**.pptx'
    #     - '**.png'

jobs:
  build:
    name: Build

    strategy:
        matrix:
            dotnet-version: [ '8.0.x' ]
            configuration: [ Release ]
            os: [ ubuntu-22.04, ubuntu-20.04 ]

   # TODO: 복수 운영체제일 때 "Generate CodeCoverage Summary Report" 중복 데이터 생성 문제
    runs-on: ${{ matrix.os }}
    #runs-on: ubuntu-22.04

    env:
        solution_dir: ./Projects/ArchiWorkshop
        solution_path: ./Projects/ArchiWorkshop/ArchiWorkshop.sln

    steps:
        # 형상관리 최신 소스 받기
        - name: Checkout
          uses: actions/checkout@v3

        # Git Commit SHA 얻기
        #   - Deprecating save-state and set-output commands: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        #   - GitHub Actions에서 output 변수의 문법 변경: https://blog.outsider.ne.kr/1651
        #   - Github Actions and creating a short SHA hash: https://dev.to/hectorleiva/github-actions-and-creating-a-short-sha-hash-8b7
        #
        # ${{ steps.vars.outputs.short_sha }}
        - name: Set short git commit SHA
          id: vars
          run: |
            calculatedSha=$(git rev-parse --short ${{ github.sha }})
            echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT

        # .NET SDK 설치
        - name: Setup .net sdk ${{ matrix.dotnet-version }}
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ matrix.dotnet-version }}

        # 패키지 복원
        - name: Restore nuget packages
          run: |
            dotnet restore ${{ env.solution_path }}

        # 빌드
        - name: Build
          run: |
            dotnet build ${{ env.solution_path }} \
                --configuration ${{ matrix.configuration }} \
                --no-restore

        #
        # 테스트 결과 폴더 구성
        #
        #  /home/runner/work/ArchiWorkshop
        #    /ArchiWorkshop                                     // 저장소 Root
        #    /Projects
        #    /ArchiWorkshop                                     // 솔루션 Root
        #       /TestResults                                    // 테스트 자동화 결과
        #           /19f5be57-f7f1-4902-a22d-ca2dcd8fdc7a       // dotnet test: 코드 커버리지 N개           <- Artifacts 업로드
        #               /coverage.cobertura.xml
        #
        #               /merged-coverage.cobertura.xml          // dotnet-coverage: Merged 코드 커버리지
        #
        #               /CodeCoverageReport                     // ReportGenerator: 코드 커버리지 Markdown  <- Summary 업로드
        #                   /SummaryGithub.md

        # 테스트 & 코드 커버리지 .cobertura 파일 생성
        - name: Test
          run: |
            dotnet test ${{ env.solution_path }} \
                --configuration ${{ matrix.configuration }} \
                --results-directory ${{ env.solution_dir }}/TestResults \
                --no-build \
                --collect "XPlat Code Coverage" \
                --verbosity normal

        # dotnet-coverage 도구 설치
        - name: Install dotnet-coverage
          run: dotnet tool install -g dotnet-coverage

        # Merged 코드 커버리지 파일 생성
        - name: Convert .coverage report to cobertura
          run: |
            dotnet-coverage merge ${{ env.solution_dir }}/TestResults/**/*.cobertura.xml \
                -f cobertura \
                -o ${{ env.solution_dir }}/TestResults/merged-coverage.cobertura.xml

        # 코드 커버리지 Markdown 파일 생성
        - name: Create coverage markdown file
          uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
          with:
            reports: '${{ env.solution_dir }}/TestResults/merged-coverage.cobertura.xml'
            targetdir: '${{ env.solution_dir }}/TestResults/CodeCoverageReport'
            reporttypes: 'MarkdownSummaryGithub'

        # 코드 커버리지 Markdown 파일 Summary 업로드
        - name: Upload coverage markdown into github actions summary
          run: cat ${{ env.solution_dir }}/TestResults/CodeCoverageReport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

        # 코드 커버리지 .cobertura 파일 Artifacts 업로드
        - name: Upload coverage files into github actions artifacts
          uses: actions/upload-artifact@v3
          with:
            name: CodeCoverageReport_${{ matrix.dotnet-version }}_sha-${{ steps.vars.outputs.short_sha }}
            path: ${{ env.solution_dir }}/TestResults/**/*.cobertura.xml

#
# 참고 자료
#
# - [x] GitHub Actions で .NETプロジェクトのコードカバレッジを計測する
#       https://zenn.dev/shimat/articles/03ad92427cbed6
# - [x] ReportGenerator Usage 자동 생성
#       https://reportgenerator.io/usage
# - [x] GitHub Actions 적용 사례
#   - https://github.com/microsoft/teams-ai/blob/main/.github/workflows/dotnet-ci.yml
# - [x] Git SHA
#   - Github Actions and creating a short SHA hash: https://dev.to/hectorleiva/github-actions-and-creating-a-short-sha-hash-8b7
# - [x] GitHub outputs 환경 변수
#   - GitHub Actions의 잡 요약($GITHUB_STEP_SUMMARY) 기능: https://blog.outsider.ne.kr/1594
#   - Deprecating save-state and set-output commands: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
#   - GitHub Actions에서 output 변수의 문법 변경: https://blog.outsider.ne.kr/1651

# - [x] 파일 찾은 후 복사하기
#   ```
#   - name: Find coverage output path
#     run: |
#       cp $(find . -name "coverage.cobertura.xml") .
#
# - [x] run 복수 명령
#   ```
#   run: |
#   ```
# - [x] run 한 명령 복수 라인
#   ```
#   run: |
#     명령 \
#       --옵션 \
#       --옵션 \
#   ```