@hostname=localhost
@port=65380
@host = http://{{hostname}}:{{port}}
@contentType = application/json

### Success
GET {{host}}/api/greeting/foo

### Success
GET {{host}}/api/users/foo

### Failure | Validation
GET {{host}}/api/users/1234567890123456789012345678901

### Failure | Exception
GET {{host}}/api/users/throw
